"""Optional LLM augmentation for open-text answers.

This is *off by default* — the template engine already produces coherent,
varied free text for free, so the deliverable runs with zero API cost. When
enabled with ``--llm``, this module rewrites only the open-text field into more
naturally-varied prose.

Two providers are supported and selected with ``--llm-provider``:

  * ``gemini``  — Google Gemini (default; model gemini-2.5-flash-lite, generous free tier)
  * ``claude``  — Anthropic Claude (model: Haiku, cheap + fast)

The provider only changes *which API makes the call*. Everything that owns
coherence — the prompt, the per-respondent conditioning, the JSON contract and
the graceful fallback — is shared, so both providers behave identically and the
structured numeric answers are never touched.

Why this is "more than a single naive prompt" (per the brief):

  1. CONDITIONING — every call is grounded in the respondent's already-decided
     structured answers (persona, rating, NPS, category, delivery). The model
     is asked to stay consistent with them, so the LLM cannot drift away from
     the coherent numeric core the statistical engine produced.
  2. ROLE + STYLE CONTROL — a system prompt fixes the persona's voice, length,
     and register.
  3. BATCHING — respondents are sent in batches to stay well inside the budget
     (Claude additionally caches the system prompt); a deterministic fallback
     keeps output flowing if a call fails.

The structured answers are *never* generated by the LLM — only the prose — so
coherence is owned by the statistical model and merely *expressed* by the LLM.
"""

from __future__ import annotations

import json
import os
import random
import re
import sys
import time
from typing import Any, Callable

from .schema import Survey

# Per-provider default model. Both are the cheap/fast tier — short prose does
# not need a frontier model, and this keeps a 200-row run well under budget.
# Gemini default is *flash-lite*: it is purpose-built for high-volume, low-cost
# text and carries the most generous free-tier quota, so a 200-row run is far
# less likely to hit the rate limits that the full flash model runs into.
DEFAULT_MODELS = {
    "gemini": "gemini-2.5-flash-lite",
    "claude": "claude-haiku-4-5-20251001",
}
# Gemini is the default: its free tier comfortably covers a 200-row run.
DEFAULT_PROVIDER = "gemini"

# Kept for backwards compatibility with anything importing the old name.
DEFAULT_MODEL = DEFAULT_MODELS[DEFAULT_PROVIDER]


class LLMUnavailable(RuntimeError):
    pass


# Substrings (case-insensitive) that mark a *transient* server hiccup worth
# retrying: overload and gateway/timeout errors. These are server-side failures
# that typically do NOT consume your request quota, and a short back-off often
# clears them — so retrying is both safe and budget-neutral.
#
# Deliberately NOT here: 429 / quota / rate-limit. Those mean you've hit a hard
# usage cap that a few seconds of back-off will not fix, so retrying just burns
# more of your free-tier budget (4 retries × 10 batches = 40 wasted requests).
# We treat them as non-retryable and abort the run early instead (see below).
_TRANSIENT_MARKERS = (
    "503", "500", "502", "504",
    "unavailable", "overloaded", "high demand",
    "timeout", "timed out", "deadline", "temporarily",
)

# A hard usage-cap error: stop calling the provider immediately to save budget.
_QUOTA_MARKERS = ("429", "resource_exhausted", "quota", "rate limit", "rate_limit")


def _is_transient(exc: Exception) -> bool:
    s = str(exc).lower()
    return any(m in s for m in _TRANSIENT_MARKERS)


def _is_quota_error(exc: Exception) -> bool:
    s = str(exc).lower()
    return any(m in s for m in _QUOTA_MARKERS)


# These open-text answers are 1–2 casual sentences. Anything dramatically longer,
# or containing fragments of our own instructions, is the model misbehaving
# (e.g. echoing the system prompt) — we reject it and keep the template draft.
_MAX_OPEN_TEXT_LEN = 240
_JUNK_MARKERS = (
    "json array", "i will return", "i am going to provide", "i'll provide",
    "as an ai", "respondent", "structured answer", "system prompt",
    "here are the", "rewrite each",
)


def _clean_text(s: str | None) -> str | None:
    """Normalise one LLM-returned answer, or return None if it's unusable.

    Collapses stray newlines/tabs/repeated spaces (flash-lite sometimes injects
    them) into single spaces. Returns ``None`` when the text is implausibly long
    or has clearly leaked our instructions, signalling the caller to keep the
    deterministic template draft for that row. An empty string is a *valid*
    answer (a happy respondent leaving the field blank)."""
    if s is None:
        return None
    text = re.sub(r"\s+", " ", str(s)).strip()
    if text == "":
        return ""  # legitimately blank
    if len(text) > _MAX_OPEN_TEXT_LEN:
        return None
    low = text.lower()
    if any(marker in low for marker in _JUNK_MARKERS):
        return None
    return text


def _call_with_retry(
    call_model: Callable[[str, str], str],
    system: str,
    prompt: str,
    *,
    retries: int = 4,
    base_delay: float = 1.0,
) -> str:
    """Call the model, retrying transient failures with exponential back-off.

    The open-text call is idempotent, so retrying is safe. Raises the last
    exception if every attempt fails or the error is non-transient.
    """
    last_exc: Exception | None = None
    for attempt in range(retries):
        try:
            return call_model(system, prompt)
        except Exception as exc:  # noqa: BLE001 - provider SDKs raise varied types
            last_exc = exc
            # Don't burn retries on errors that won't fix themselves.
            if not _is_transient(exc) or attempt == retries - 1:
                raise
            delay = base_delay * (2 ** attempt) + random.uniform(0, 0.4)
            time.sleep(delay)
    raise last_exc  # pragma: no cover - loop always returns or raises above


def augment_open_text(
    survey: Survey,
    responses: list[dict[str, Any]],
    provider: str = DEFAULT_PROVIDER,
    model: str | None = None,
    batch_size: int = 20,
    retries: int = 4,
    verbose: bool = True,
) -> list[dict[str, Any]]:
    """Rewrite the open-feedback field of each response using an LLM.

    ``provider`` is ``"gemini"`` (default) or ``"claude"``. ``model`` overrides
    the provider default. Transient server errors (503/overload/timeout) are
    retried with exponential back-off; a batch that still fails falls back to
    the existing template text so a flaky network never breaks generation. A
    hard usage/quota limit (429) is NOT retried — it aborts the LLM pass early
    so a capped run spends one request instead of forty. A missing package or
    API key raises ``LLMUnavailable`` up front so the CLI can print a notice and
    continue with the (free) template engine.

    Unlike a silent fallback, this **reports** what happened: every failed batch
    is logged and a final summary line states how many batches succeeded and how
    many open-text answers were actually rewritten — so a run that quietly fell
    back to template text can never masquerade as a successful LLM run.
    """
    provider = (provider or DEFAULT_PROVIDER).lower()
    if provider not in DEFAULT_MODELS:
        raise LLMUnavailable(
            f"Unknown LLM provider {provider!r}. Choose one of "
            f"{sorted(DEFAULT_MODELS)}."
        )
    model = model or DEFAULT_MODELS[provider]

    q_txt = survey.by_role("open_feedback")
    if q_txt is None:
        return responses  # nothing to augment

    # Build the provider-specific caller once. This validates the package + key
    # and raises LLMUnavailable before we touch any data.
    call_model = _make_caller(provider, model)
    system = _system_prompt(survey)

    planned_batches = (len(responses) + batch_size - 1) // batch_size
    succeeded_batches = 0
    rewritten_rows = 0
    quota_hit = False

    for start in range(0, len(responses), batch_size):
        batch = responses[start : start + batch_size]
        end = start + len(batch) - 1
        prompt = _batch_prompt(survey, batch, q_txt.id)
        try:
            text = _call_with_retry(call_model, system, prompt, retries=retries)
            rewritten = _parse_batch_reply(text)
            if not rewritten:
                raise ValueError("empty or unparseable reply from the model")
            for resp, new_text in zip(batch, rewritten):
                if new_text is None:
                    continue  # parser had no entry for this row
                cleaned = _clean_text(new_text)
                if cleaned is None:
                    continue  # model returned junk here; keep template draft
                resp[q_txt.id] = cleaned
                rewritten_rows += 1
            succeeded_batches += 1
        except Exception as exc:  # keep generation resilient, but be loud about it
            # A hard usage cap (429/quota) won't clear on a retry and will fail
            # every remaining batch identically. Stop now so the run spends one
            # request, not ten — protecting the free-tier budget.
            if _is_quota_error(exc):
                quota_hit = True
                if verbose:
                    print(
                        f"[llm] rows {start}-{end}: hit a usage/quota limit "
                        f"({type(exc).__name__}). Stopping further LLM calls to "
                        f"protect your free-tier budget; remaining rows keep "
                        f"template text.",
                        file=sys.stderr,
                    )
                break
            if verbose:
                print(
                    f"[llm] rows {start}-{end}: failed after {retries} attempt(s) "
                    f"({type(exc).__name__}: {str(exc)[:90]}); kept template text.",
                    file=sys.stderr,
                )
            continue  # keep template text for this batch

    if verbose:
        fell_back = planned_batches - succeeded_batches
        msg = (
            f"[llm] {succeeded_batches}/{planned_batches} batches succeeded — "
            f"{rewritten_rows} open-text answer(s) rewritten by the LLM."
        )
        if fell_back:
            reason = (
                "stopped early on a usage/quota limit"
                if quota_hit
                else "provider unavailable"
            )
            msg += f" {fell_back} batch(es) used template text ({reason})."
        print(msg, file=sys.stderr)

    return responses


# --------------------------------------------------------------------------- #
# Provider callers
#
# Each builds its client (validating package + key) and returns a closure
# call(system, prompt) -> str. Keeping the wiring behind a uniform signature is
# what lets the batching loop above stay provider-agnostic.
# --------------------------------------------------------------------------- #
def _make_caller(provider: str, model: str) -> Callable[[str, str], str]:
    if provider == "gemini":
        return _gemini_caller(model)
    if provider == "claude":
        return _claude_caller(model)
    raise LLMUnavailable(f"Unsupported provider {provider!r}.")  # pragma: no cover


def _gemini_caller(model: str) -> Callable[[str, str], str]:
    try:
        from google import genai  # type: ignore
        from google.genai import types  # type: ignore
    except ImportError as exc:
        raise LLMUnavailable(
            "The 'google-genai' package is not installed. Run "
            "`pip install google-genai`, or omit --llm to use the (free) "
            "template engine."
        ) from exc

    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise LLMUnavailable(
            "GEMINI_API_KEY (or GOOGLE_API_KEY) is not set. Get a free key at "
            "https://aistudio.google.com/apikey and export it, or omit --llm to "
            "use the (free) template engine."
        )

    client = genai.Client(api_key=api_key)

    def call(system: str, prompt: str) -> str:
        resp = client.models.generate_content(
            model=model,
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=system,
                temperature=1.0,
                # Force a JSON array of strings so the shared parser can read it
                # straight back without coaxing fenced code blocks out of it.
                response_mime_type="application/json",
                response_schema=list[str],
            ),
        )
        return resp.text or ""

    return call


def _claude_caller(model: str) -> Callable[[str, str], str]:
    try:
        import anthropic  # type: ignore
    except ImportError as exc:
        raise LLMUnavailable(
            "The 'anthropic' package is not installed. Run `pip install anthropic`, "
            "use the default --llm-provider gemini, or omit --llm to use the "
            "(free) template engine."
        ) from exc

    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise LLMUnavailable(
            "ANTHROPIC_API_KEY is not set. Export it, use the default "
            "--llm-provider gemini, or omit --llm to use the (free) template engine."
        )

    client = anthropic.Anthropic()

    def call(system: str, prompt: str) -> str:
        msg = client.messages.create(
            model=model,
            max_tokens=1500,
            temperature=1.0,
            system=[
                {"type": "text", "text": system, "cache_control": {"type": "ephemeral"}}
            ],
            messages=[{"role": "user", "content": prompt}],
        )
        return "".join(b.text for b in msg.content if b.type == "text")

    return call


# --------------------------------------------------------------------------- #
# Shared prompt construction + parsing (provider-agnostic)
# --------------------------------------------------------------------------- #
def _system_prompt(survey: Survey) -> str:
    return (
        "You write short, authentic-sounding open-text answers for a customer "
        "satisfaction survey, in the voice of the specific respondent described. "
        "Rules:\n"
        "- Stay strictly consistent with the respondent's structured answers "
        "(their rating, recommend score, category and whether delivery was on "
        "time). Never contradict them.\n"
        "- Match the sentiment to the rating: high rating = warm/brief, mid = "
        "balanced, low = frustrated and specific.\n"
        "- If delivery was late, it is natural (not mandatory) to mention it.\n"
        "- 1–2 sentences, casual, no marketing speak, occasional minor "
        "imperfection is fine. Some happy respondents write almost nothing.\n"
        "- Return ONLY a JSON array of strings, one per respondent, same order."
    )


def _batch_prompt(survey: Survey, batch: list[dict[str, Any]], txt_id: str) -> str:
    q_sat = survey.by_role("satisfaction")
    q_nps = survey.by_role("nps")
    q_cat = survey.by_role("category")
    q_del = survey.by_role("delivery_on_time")

    rows = []
    for r in batch:
        rows.append(
            {
                "persona": r.get("_persona"),
                "satisfaction": r.get(q_sat.id) if q_sat else None,
                "recommend": r.get(q_nps.id) if q_nps else None,
                "category": r.get(q_cat.id) if q_cat else None,
                "delivery_on_time": r.get(q_del.id) if q_del else None,
                "draft": r.get(txt_id, ""),
            }
        )
    return (
        f'Question: "What could we improve?"\n\n'
        "Here are respondents and their structured answers. Rewrite each one's "
        "open-text answer to sound natural while staying consistent. Keep blanks "
        "blank for clearly-happy respondents who would not bother.\n\n"
        + json.dumps(rows, indent=2)
        + "\n\nReturn a JSON array of exactly "
        + str(len(rows))
        + " strings."
    )


def _parse_batch_reply(text: str) -> list[str | None]:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1].rsplit("```", 1)[0]
    try:
        data = json.loads(text)
        if isinstance(data, list):
            return [str(x) if x is not None else None for x in data]
    except json.JSONDecodeError:
        pass
    return []
